version: '3.8'

services:
  python-service:
    build: .
    volumes:
      - ./logs:/task/logs  # Синхронізація папки з логами між контейнером та локальним диском
    ports:
      - "5000:5000"  # Якщо потрібно пробросити порти
